kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3.6.3-jdk-11
    commands:
     - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
     - mvn test -B
     - mvn package -DskipTests=true
    trigger:
      branch:
        - develop
        - master
        - f-ci-jar-download-steps

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: /drone/src/target/theroomapp*.jar
    when:
      event: tag

  - name: notify
    image: plugins/slack-blame
    settings:
      token:
        from_secret: slack-token
      channel: drone
      success_template: |
        The build is fixed! Thanks @{{user.name}}
      failure_template: |
        The build is broken! Blame {{user.name}}