kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3.6.3-jdk-11
    commands:
     - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
     - mvn test -B
     - mvn package -DskipTests=true
    trigger:
      branch:
        - develop
        - master
        - f-drone-coverage-plugin

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - jacoco.xml
      paths:
        - /drone/src/target/site/jacoco/

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack-webhook
      channel: drone
    when:
      status: [ success, failure ]

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: /drone/src/target/theroomapp-*-SNAPSHOT.jar
    when:
      event: tag